------------------------------------------------------------------------------
-- Atelier / Helix — Memory schema
--
-- Target: SQLite >= 3.38 (JSON1 built in, partial indexes, upserts).
-- Loaded verbatim by store.py (executescript); every statement is idempotent.
--
-- Conventions
--   * ids          TEXT, prefixed ULIDs generated by store.py ('prj_01J…').
--   * timestamps   INTEGER, unix epoch milliseconds, UTC.
--   * *_json       TEXT holding one JSON document, guarded by json_valid().
--   * archival     projects and threads are archived, never hard-deleted.
--
-- The two strands of the helix:
--   INTENT  = threads + messages          (what was asked, decided, said)
--   MATTER  = artifacts                   (what was made)
-- and the rungs that bind them:
--   rungs   = message <-> artifact provenance links.
--
-- Invariants enforced at this layer (numbering matches ARCHITECTURE.md):
--   I2  secrets never touch this file: provider_configs stores key_ref only
--       (shape-checked here, content-scanned in store.py).
--   I3  messages are append-only                      -> triggers
--   I4  artifact content & provenance are frozen      -> trigger
--   I5  an 'artifact' node must reference an artifact -> CHECK
--   I6  at most one active brand kit per project      -> partial unique index
--   I8  usage_events is an append-only ledger         -> triggers
------------------------------------------------------------------------------

PRAGMA user_version = 1;

------------------------------------------------------------------------------
-- Projects: the root aggregate. Everything else hangs off a project.
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
    slug        TEXT NOT NULL UNIQUE
                CHECK (length(slug) BETWEEN 1 AND 80
                       AND slug NOT GLOB '*[^a-z0-9-]*'),
    description TEXT NOT NULL DEFAULT '',
    meta_json   TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(meta_json)),
    archived_at INTEGER,                      -- NULL = active
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
);

------------------------------------------------------------------------------
-- Intent strand: threads and messages.
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS threads (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id),
    title      TEXT NOT NULL DEFAULT 'Untitled thread',
    status     TEXT NOT NULL DEFAULT 'open'
               CHECK (status IN ('open', 'pinned', 'resolved', 'archived')),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_threads_project
    ON threads (project_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS messages (
    id           TEXT PRIMARY KEY,
    thread_id    TEXT NOT NULL REFERENCES threads(id),
    seq          INTEGER NOT NULL CHECK (seq >= 0),   -- per-thread, gap-free
    role         TEXT NOT NULL
                 CHECK (role IN ('user', 'conductor', 'spoke', 'system', 'note')),
    content      TEXT NOT NULL,                       -- canonical human-readable text
    payload_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload_json)),
    created_at   INTEGER NOT NULL,
    UNIQUE (thread_id, seq)
);

CREATE INDEX IF NOT EXISTS ix_messages_thread
    ON messages (thread_id, seq);

-- I3: the intent strand is a ledger. History is never rewritten.
CREATE TRIGGER IF NOT EXISTS trg_messages_no_update
BEFORE UPDATE ON messages
BEGIN
    SELECT RAISE(ABORT, 'helix I3: messages are append-only');
END;

CREATE TRIGGER IF NOT EXISTS trg_messages_no_delete
BEFORE DELETE ON messages
BEGIN
    SELECT RAISE(ABORT, 'helix I3: messages are append-only');
END;

------------------------------------------------------------------------------
-- Spokes: provider configurations (BYOK).
-- key_ref is an opaque Keyring handle, e.g. 'openai.personal'. The raw secret
-- lives in the OS keychain / encrypted keyfile managed by the Keyring module
-- and is scanned-for and rejected by store.py before any row lands here (I2).
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS provider_configs (
    id                TEXT PRIMARY KEY,
    spoke             TEXT NOT NULL
                      CHECK (spoke = lower(spoke)
                             AND length(spoke) BETWEEN 2 AND 40
                             AND spoke NOT GLOB '*[^a-z0-9_-]*'),
    label             TEXT NOT NULL UNIQUE,
    base_url          TEXT,
    key_ref           TEXT
                      CHECK (key_ref IS NULL
                             OR (length(key_ref) BETWEEN 3 AND 64
                                 AND key_ref NOT GLOB '*[^a-z0-9_.:-]*')),
    enabled           INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    capabilities_json TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(capabilities_json)),
    defaults_json     TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(defaults_json)),
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_provider_configs_spoke
    ON provider_configs (spoke, enabled);

------------------------------------------------------------------------------
-- Loom: media pipeline runs and their steps.
-- A run is a small DAG of steps; each step is one spoke operation.
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS loom_runs (
    id          TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL REFERENCES projects(id),
    thread_id   TEXT REFERENCES threads(id),
    name        TEXT NOT NULL DEFAULT 'run',
    plan_json   TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(plan_json)),
    status      TEXT NOT NULL DEFAULT 'queued'
                CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    error       TEXT,
    created_at  INTEGER NOT NULL,
    started_at  INTEGER,
    finished_at INTEGER
);

CREATE INDEX IF NOT EXISTS ix_loom_runs_project
    ON loom_runs (project_id, created_at DESC);

CREATE TABLE IF NOT EXISTS loom_steps (
    id                 TEXT PRIMARY KEY,
    run_id             TEXT NOT NULL REFERENCES loom_runs(id),
    idx                INTEGER NOT NULL CHECK (idx >= 0),
    name               TEXT NOT NULL,
    spoke_op           TEXT NOT NULL,        -- 'image.generate', 'image.upscale', …
    provider_config_id TEXT REFERENCES provider_configs(id),
    params_json        TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(params_json)),
    status             TEXT NOT NULL DEFAULT 'queued'
                       CHECK (status IN ('queued', 'running', 'succeeded',
                                         'failed', 'cancelled', 'skipped')),
    error              TEXT,
    started_at         INTEGER,
    finished_at        INTEGER,
    UNIQUE (run_id, idx)
);

------------------------------------------------------------------------------
-- Matter strand: artifacts. Content-addressed and immutable once written.
-- 'blob' rows point into the content-addressed blob root managed by store.py;
-- 'external' rows point at a URL the user registered.
-- parent_id records derivation (upscale-of, variation-of, crop-of, …).
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS artifacts (
    id          TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL REFERENCES projects(id),
    kind        TEXT NOT NULL
                CHECK (kind IN ('image', 'video', 'audio', 'vector', 'text',
                                'font', 'model3d', 'archive', 'other')),
    mime        TEXT NOT NULL,
    storage     TEXT NOT NULL CHECK (storage IN ('blob', 'external')),
    uri         TEXT NOT NULL,   -- blob: '<sha[:2]>/<sha>' relative path; external: URL
    sha256      TEXT CHECK (sha256 IS NULL
                            OR (length(sha256) = 64
                                AND sha256 NOT GLOB '*[^0-9a-f]*')),
    byte_size   INTEGER CHECK (byte_size IS NULL OR byte_size >= 0),
    width       INTEGER CHECK (width IS NULL OR width > 0),
    height      INTEGER CHECK (height IS NULL OR height > 0),
    duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
    title       TEXT NOT NULL DEFAULT '',
    meta_json   TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(meta_json)),
    parent_id   TEXT REFERENCES artifacts(id),
    created_at  INTEGER NOT NULL,
    CHECK (storage <> 'blob' OR sha256 IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_artifacts_project
    ON artifacts (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_artifacts_sha
    ON artifacts (sha256) WHERE sha256 IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_artifacts_parent
    ON artifacts (parent_id) WHERE parent_id IS NOT NULL;

-- I4: matter is immutable; only annotations (title, meta_json) may change.
CREATE TRIGGER IF NOT EXISTS trg_artifacts_frozen
BEFORE UPDATE OF project_id, kind, mime, storage, uri, sha256, byte_size,
                 width, height, duration_ms, parent_id, created_at
ON artifacts
BEGIN
    SELECT RAISE(ABORT, 'helix I4: artifact content and provenance are frozen');
END;

------------------------------------------------------------------------------
-- Rungs: the cross-links that hold the two strands together.
-- Every artifact's "why" is discoverable through its rungs.
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rungs (
    id          TEXT PRIMARY KEY,
    message_id  TEXT NOT NULL REFERENCES messages(id),
    artifact_id TEXT NOT NULL REFERENCES artifacts(id),
    relation    TEXT NOT NULL
                CHECK (relation IN ('prompted', 'produced', 'referenced',
                                    'approved', 'rejected')),
    created_at  INTEGER NOT NULL,
    UNIQUE (message_id, artifact_id, relation)
);

CREATE INDEX IF NOT EXISTS ix_rungs_artifact ON rungs (artifact_id);

------------------------------------------------------------------------------
-- Loom step I/O: which artifacts a step consumed and produced.
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS loom_step_io (
    step_id     TEXT NOT NULL REFERENCES loom_steps(id),
    artifact_id TEXT NOT NULL REFERENCES artifacts(id),
    direction   TEXT NOT NULL CHECK (direction IN ('input', 'output')),
    PRIMARY KEY (step_id, artifact_id, direction)
);

------------------------------------------------------------------------------
-- Board: infinite canvas. Boards/layers/nodes are mutable *projections* of
-- the helix — deleting a node never deletes the artifact behind it.
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS boards (
    id            TEXT PRIMARY KEY,
    project_id    TEXT NOT NULL REFERENCES projects(id),
    name          TEXT NOT NULL DEFAULT 'Board',
    viewport_json TEXT NOT NULL DEFAULT '{"x":0,"y":0,"zoom":1}'
                  CHECK (json_valid(viewport_json)),
    created_at    INTEGER NOT NULL,
    updated_at    INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_boards_project ON boards (project_id);

CREATE TABLE IF NOT EXISTS board_layers (
    id         TEXT PRIMARY KEY,
    board_id   TEXT NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
    name       TEXT NOT NULL DEFAULT 'Layer',
    z_index    INTEGER NOT NULL DEFAULT 0,
    visible    INTEGER NOT NULL DEFAULT 1 CHECK (visible IN (0, 1)),
    locked     INTEGER NOT NULL DEFAULT 0 CHECK (locked IN (0, 1)),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_board_layers_board
    ON board_layers (board_id, z_index);

CREATE TABLE IF NOT EXISTS board_nodes (
    id          TEXT PRIMARY KEY,
    board_id    TEXT NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
    layer_id    TEXT NOT NULL REFERENCES board_layers(id) ON DELETE CASCADE,
    kind        TEXT NOT NULL
                CHECK (kind IN ('artifact', 'text', 'shape', 'frame',
                                'sticky', 'connector')),
    artifact_id TEXT REFERENCES artifacts(id),
    x           REAL NOT NULL DEFAULT 0,
    y           REAL NOT NULL DEFAULT 0,
    w           REAL NOT NULL DEFAULT 100 CHECK (w >= 0),
    h           REAL NOT NULL DEFAULT 100 CHECK (h >= 0),
    rotation    REAL NOT NULL DEFAULT 0,
    opacity     REAL NOT NULL DEFAULT 1 CHECK (opacity BETWEEN 0 AND 1),
    z           REAL NOT NULL DEFAULT 0,       -- fractional order within layer
    props_json  TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(props_json)),
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL,
    -- I5: an artifact node without an artifact is meaningless.
    CHECK (kind <> 'artifact' OR artifact_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_board_nodes_board
    ON board_nodes (board_id, layer_id, z);

------------------------------------------------------------------------------
-- Brand kits: reusable identity (palette, typography, voice) plus curated
-- artifact references (logos, textures, reference imagery).
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS brand_kits (
    id              TEXT PRIMARY KEY,
    project_id      TEXT NOT NULL REFERENCES projects(id),
    name            TEXT NOT NULL,
    is_active       INTEGER NOT NULL DEFAULT 0 CHECK (is_active IN (0, 1)),
    palette_json    TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(palette_json)),
    typography_json TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(typography_json)),
    voice_json      TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(voice_json)),
    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL
);

-- I6: at most one active brand kit per project.
CREATE UNIQUE INDEX IF NOT EXISTS ux_brand_kits_active
    ON brand_kits (project_id) WHERE is_active = 1;

CREATE TABLE IF NOT EXISTS brand_assets (
    id           TEXT PRIMARY KEY,
    brand_kit_id TEXT NOT NULL REFERENCES brand_kits(id) ON DELETE CASCADE,
    artifact_id  TEXT NOT NULL REFERENCES artifacts(id),
    role         TEXT NOT NULL DEFAULT 'reference'
                 CHECK (role IN ('logo_primary', 'logo_mark', 'wordmark',
                                 'texture', 'reference', 'other')),
    created_at   INTEGER NOT NULL,
    UNIQUE (brand_kit_id, artifact_id, role)
);

------------------------------------------------------------------------------
-- Usage events: the metering ledger. Every spoke call lands one row.
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usage_events (
    id                 TEXT PRIMARY KEY,
    created_at         INTEGER NOT NULL,
    project_id         TEXT REFERENCES projects(id),
    thread_id          TEXT REFERENCES threads(id),
    run_id             TEXT REFERENCES loom_runs(id),
    step_id            TEXT REFERENCES loom_steps(id),
    provider_config_id TEXT REFERENCES provider_configs(id),
    spoke              TEXT NOT NULL,
    operation          TEXT NOT NULL,          -- 'text.generate', 'image.generate', …
    model              TEXT,
    unit_type          TEXT NOT NULL DEFAULT 'requests'
                       CHECK (unit_type IN ('tokens', 'pixels', 'seconds',
                                            'characters', 'requests')),
    input_units        INTEGER NOT NULL DEFAULT 0 CHECK (input_units >= 0),
    output_units       INTEGER NOT NULL DEFAULT 0 CHECK (output_units >= 0),
    cost_micros        INTEGER NOT NULL DEFAULT 0 CHECK (cost_micros >= 0),
    latency_ms         INTEGER CHECK (latency_ms IS NULL OR latency_ms >= 0),
    status             TEXT NOT NULL DEFAULT 'ok'
                       CHECK (status IN ('ok', 'error', 'cancelled')),
    error              TEXT,
    meta_json          TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(meta_json))
);

CREATE INDEX IF NOT EXISTS ix_usage_project
    ON usage_events (project_id, created_at);
CREATE INDEX IF NOT EXISTS ix_usage_spoke
    ON usage_events (spoke, operation, created_at);

-- I8: the meter never lies. No edits, no deletions.
CREATE TRIGGER IF NOT EXISTS trg_usage_no_update
BEFORE UPDATE ON usage_events
BEGIN
    SELECT RAISE(ABORT, 'helix I8: usage_events is append-only');
END;

CREATE TRIGGER IF NOT EXISTS trg_usage_no_delete
BEFORE DELETE ON usage_events
BEGIN
    SELECT RAISE(ABORT, 'helix I8: usage_events is append-only');
END;

------------------------------------------------------------------------------
-- Views
------------------------------------------------------------------------------
CREATE VIEW IF NOT EXISTS v_usage_daily AS
SELECT
    date(created_at / 1000, 'unixepoch') AS day,
    spoke,
    operation,
    COUNT(*)          AS events,
    SUM(input_units)  AS input_units,
    SUM(output_units) AS output_units,
    SUM(cost_micros)  AS cost_micros
FROM usage_events
GROUP BY day, spoke, operation;

CREATE VIEW IF NOT EXISTS v_board_scene AS
SELECT
    n.id          AS node_id,
    n.board_id    AS board_id,
    l.id          AS layer_id,
    l.name        AS layer_name,
    l.z_index     AS layer_z,
    l.visible     AS layer_visible,
    l.locked      AS layer_locked,
    n.z           AS node_z,
    n.kind        AS kind,
    n.x, n.y, n.w, n.h, n.rotation, n.opacity,
    n.artifact_id AS artifact_id,
    a.kind        AS artifact_kind,
    a.mime        AS artifact_mime,
    a.uri         AS artifact_uri,
    n.props_json  AS props_json
FROM board_nodes n
JOIN board_layers l ON l.id = n.layer_id
LEFT JOIN artifacts a ON a.id = n.artifact_id;
