#!/usr/bin/env python3
"""Assemble top100.json from fetched repo data + curated metadata."""
import json

data = json.load(open("/tmp/atelier-fable/02-top100/repo_data.json"))
# index by canonical nameWithOwner too (repos that moved orgs)
for v in list(data.values()):
    data.setdefault(v["repo"], v)

# Late additions fetched separately (2025-2026 projects)
data["onlook-dev/onlook"] = {"repo": "onlook-dev/onlook", "stars": 26528, "license": "Apache-2.0"}
data["Wan-Video/Wan2.2"] = {"repo": "Wan-Video/Wan2.2", "stars": 17238, "license": "Apache-2.0"}
data["QwenLM/Qwen-Image"] = {"repo": "QwenLM/Qwen-Image", "stars": 8255, "license": "Apache-2.0"}

# Canonical names after redirects (old candidate key -> canonical nameWithOwner already stored in value)
# License overrides where GitHub reports NOASSERTION/Other
LICENSE_OVERRIDES = {
    "n8n-io/n8n": "SUL-1.0 (fair-code)",
    "langgenius/dify": "Dify Open Source License (Apache-2.0 + conditions)",
    "open-webui/open-webui": "Open WebUI License (BSD-3 derived + branding clause)",
    "lobehub/lobehub": "LobeHub Community License",
    "toeverything/AFFiNE": "MIT (core) + ee",
    "remotion-dev/remotion": "Remotion License (free for individuals/small teams)",
    "BerriAI/litellm": "MIT (core) + enterprise dir",
    "tldraw/tldraw": "tldraw License (free with watermark)",
    "janhq/jan": "Apache-2.0",
    "modelcontextprotocol/servers": "MIT -> Apache-2.0 (transition)",
    "langfuse/langfuse": "MIT (core) + ee",
    "mastra-ai/mastra": "Apache-2.0 (core) + ee",
    "vercel/ai": "Apache-2.0",
    "lucide-icons/lucide": "ISC",
    "KlingAIResearch/LivePortrait": "MIT (code); model weights restricted",
    "konvajs/konva": "MIT",
    "Tencent-Hunyuan/Hunyuan3D-2": "Tencent Hunyuan Community License",
    "Tencent-Hunyuan/HunyuanVideo": "Tencent Hunyuan Community License",
    "graphdeco-inria/gaussian-splatting": "Inria/MPII research license (non-commercial)",
    "Arize-ai/phoenix": "Elastic License 2.0",
    "fishaudio/fish-speech": "Fish Audio Research License (code); weights CC-BY-NC-SA",
    "FoundationAgents/MetaGPT": "MIT",
    "microsoft/autogen": "MIT (code); CC-BY-4.0 docs",
}

# key used in repo_data.json (candidate name); value: (category, why, integrate_as)
CATALOG = {
    # ---------------- LLM routers / gateways ----------------
    "BerriAI/litellm": ("llm-router-gateway",
        "De-facto standard BYOK gateway: one OpenAI-format SDK + proxy for 100+ providers (OpenAI, Gemini, Anthropic, Ollama, any OpenAI-compatible), with virtual keys, budgets, rate limits and spend tracking.",
        "Core routing layer behind the keyring; run as sidecar proxy so every spoke speaks one dialect."),
    "songquanpeng/one-api": ("llm-router-gateway",
        "Self-hosted OpenAI-compatible gateway focused on key issuance, token quota accounting and channel load-balancing across providers; single Go binary.",
        "Alternative quota/billing gateway if LiteLLM proxy is too heavy; good reference for token metering."),
    "Portkey-AI/gateway": ("llm-router-gateway",
        "Fast (~10ms) edge-deployable AI gateway with retries, fallbacks, load balancing, guardrails and multimodal routing across 250+ models.",
        "Drop-in HTTP router option; borrow its config-as-JSON routing rules for keyring failover policies."),
    "maximhq/bifrost": ("llm-router-gateway",
        "High-throughput Go LLM gateway (microsecond overhead) with provider fallbacks, semantic caching, MCP support and governance features.",
        "Performance-tier gateway swap when self-hosting at scale; benchmark baseline for keyring latency."),
    "andrewyng/aisuite": ("llm-router-gateway",
        "Thin, dependency-light unified Python client for swapping OpenAI/Gemini/Anthropic/Ollama with one interface string like 'openai:gpt-4o'.",
        "Minimal embedded fallback when running without a proxy; pattern for provider-id naming in keyring."),
    "vercel/ai": ("llm-router-gateway",
        "Vercel AI SDK: TypeScript provider abstraction plus React hooks for streaming chat/completions and generative UI; supports OpenAI, Google, Anthropic and OpenAI-compatible endpoints.",
        "Frontend model-access layer: board talks to keyring through AI SDK providers with streamed tool-calls."),
    "simonw/llm": ("llm-router-gateway",
        "CLI + Python library with a plugin ecosystem for dozens of providers and local models; logs every prompt/response to SQLite.",
        "Dev/ops harness for smoke-testing keyring credentials and batch prompt experiments."),

    # ---------------- Agent frameworks ----------------
    "langchain-ai/langchain": ("agent-framework",
        "Largest LLM application framework; exhaustive integrations for models, tools, retrievers and output parsers.",
        "Integration library mined selectively; use its loaders/parsers inside spokes rather than whole-app adoption."),
    "langchain-ai/langgraph": ("agent-framework",
        "Low-level durable agent orchestration as stateful graphs: checkpoints, human-in-the-loop interrupts, streaming, subgraphs. Powers many production agent products.",
        "The conductor runtime: each design job is a LangGraph with persisted state and resumable steps."),
    "microsoft/autogen": ("agent-framework",
        "Microsoft multi-agent conversation framework (AgentChat, event-driven core, cross-language support).",
        "Reference for multi-agent critique loops (art-director agent reviewing generator agent output)."),
    "crewAIInc/crewAI": ("agent-framework",
        "Role-based multi-agent crews with tasks, tools and process templates; independent of LangChain.",
        "Pattern source for role prompts (Designer / Copywriter / Brand-Guardian crew presets in conductor)."),
    "huggingface/smolagents": ("agent-framework",
        "Minimal agent library where agents write Python code to act; ~1k LOC core, sandboxed execution, model-agnostic.",
        "Lightweight code-acting agent for asset-processing scripts inside sandboxed spokes."),
    "openai/openai-agents-python": ("agent-framework",
        "OpenAI Agents SDK: handoffs, guardrails, sessions and tracing; provider-agnostic (works with 100+ LLMs via LiteLLM).",
        "Conductor alternative/reference; its handoff + guardrail primitives map cleanly onto BYOK via keyring."),
    "google/adk-python": ("agent-framework",
        "Google Agent Development Kit: code-first multi-agent framework, Gemini-optimized but model-agnostic, with eval and deployment tooling.",
        "First-class Gemini path in conductor; use its tool/agent schemas when user key is Google."),
    "pydantic/pydantic-ai": ("agent-framework",
        "Type-safe agent framework from the Pydantic team: structured outputs, dependency injection, model-agnostic across OpenAI/Gemini/Anthropic/Ollama.",
        "Schema layer for conductor: every design-brief, layer-spec and asset-manifest is a validated Pydantic model."),
    "run-llama/llama_index": ("agent-framework",
        "Data framework for LLM apps: ingestion, indexing, retrieval, agent tools over private data.",
        "Memory module backbone: index brand guidelines, past projects and asset metadata for retrieval."),
    "FoundationAgents/MetaGPT": ("agent-framework",
        "Multi-agent 'software company' with SOP-driven role choreography (PRD -> design -> code).",
        "Reference for SOP-style pipelines: brief -> moodboard -> comps -> final assets as staged roles."),
    "mastra-ai/mastra": ("agent-framework",
        "TypeScript agent framework (workflows, RAG, evals, observability) from the Gatsby team; strong DX for JS-native stacks.",
        "Conductor option if Helix stays all-TypeScript; its workflow primitives suit render pipelines."),
    "agno-agi/agno": ("agent-framework",
        "High-performance multi-agent runtime with built-in memory, knowledge, tools and reasoning; strong benchmarks on instantiation speed.",
        "Candidate for lightweight per-canvas helper agents where LangGraph is overkill."),
    "CopilotKit/CopilotKit": ("agent-framework",
        "React infrastructure for in-app AI copilots: shared state with agents, generative UI, AG-UI protocol.",
        "Board <-> conductor bridge: surface agent progress and interactive suggestions inside the canvas UI."),
    "modelcontextprotocol/servers": ("agent-framework",
        "Reference implementations of Model Context Protocol servers (filesystem, fetch, git, memory...); the emerging standard for agent tool connectivity.",
        "Tool bus: expose each spoke as an MCP server so any MCP-capable model/client can drive the studio."),
    "e2b-dev/E2B": ("agent-framework",
        "Open-source secure cloud sandboxes for AI agents to run untrusted code (Firecracker microVMs).",
        "Sandbox spoke for agent-authored scripts (batch image processing, data viz, font manipulation)."),

    # ---------------- Image gen UIs ----------------
    "comfyanonymous/ComfyUI": ("image-gen-ui",
        "The most powerful modular diffusion engine: node-graph workflows, an HTTP/WebSocket API, and day-one support for nearly every open image/video model (SDXL, FLUX, Qwen-Image, Wan...).",
        "Primary local generation spoke: Helix submits workflow JSON via API; workflows stored as loom templates."),
    "AUTOMATIC1111/stable-diffusion-webui": ("image-gen-ui",
        "The historic Stable Diffusion web UI with a huge extension ecosystem; development has slowed but the API and extensions remain widely deployed.",
        "Legacy/alt image spoke via its txt2img/img2img REST API for users who already run it."),
    "lllyasviel/Fooocus": ("image-gen-ui",
        "Midjourney-like 'prompt and go' SDXL UI with built-in prompt expansion and quality presets (project frozen but stable).",
        "UX reference for the one-box generate flow; its GPT-2 prompt expansion is worth porting into spokes."),
    "invoke-ai/InvokeAI": ("image-gen-ui",
        "Professional creative studio for open image models: unified canvas, layers, regional prompts, workflow engine, model manager.",
        "Reference architecture for board<->diffusion integration (layered inpainting, canvas regions); optional spoke."),
    "Acly/krita-ai-diffusion": ("image-gen-ui",
        "Generative AI inside Krita: seamless region fill, live painting, ControlNet, using a ComfyUI backend.",
        "Pattern donor for pro-tool integration; proves the ComfyUI-as-backend spoke model Helix uses."),
    "huggingface/diffusers": ("image-gen-ui",
        "The standard Python library for diffusion pipelines across image/video/audio; every new model lands here.",
        "Direct-pipeline spoke for headless batch generation where a full ComfyUI graph is unnecessary."),
    "black-forest-labs/flux": ("image-gen-ui",
        "Official inference repo for the FLUX.1/FLUX.2 family (dev/schnell/Kontext) - the strongest open image models.",
        "Model backend consumed through ComfyUI/diffusers spokes; Kontext powers instruction-based image edits."),
    "QwenLM/Qwen-Image": ("image-gen-ui",
        "Apache-2.0 image generation + editing foundation model with best-in-class text rendering (incl. CJK) - critical for poster/brand work.",
        "Text-heavy design spoke (posters, packaging, logotype comps) via diffusers or ComfyUI nodes."),
    "Sanster/IOPaint": ("image-gen-ui",
        "Best standalone inpainting/eraser tool (LaMa, SD, remove-anything) with clean web UI and API. Archived 2025 but stable and widely deployed.",
        "Object-removal microservice spoke; pin version and wrap its FastAPI endpoints."),
    "upscayl/upscayl": ("image-gen-ui",
        "Cross-platform desktop AI upscaler built on Real-ESRGAN/NCNN; the consumer standard for local upscaling.",
        "Desktop companion + CLI (upscayl-ncnn) callable as an upscale spoke for final asset export."),
    "xinntao/Real-ESRGAN": ("image-gen-ui",
        "The reference super-resolution models/algorithms for practical image restoration.",
        "Upscale spoke primitive: run ncnn/PyTorch weights server-side for 2x-4x asset export."),
    "danielgatis/rembg": ("image-gen-ui",
        "One-command background removal (U2Net/BiRefNet) as a Python lib, CLI and Docker HTTP server.",
        "Cutout spoke: containerized rembg endpoint for product shots, sticker generation, layer extraction."),

    # ---------------- Video ----------------
    "Tencent-Hunyuan/HunyuanVideo": ("video",
        "13B open video generation model with strong motion quality; large ecosystem (ComfyUI nodes, LoRAs, distills).",
        "Local text-to-video spoke via ComfyUI workflow; community license permits <100M MAU commercial use."),
    "Wan-Video/Wan2.2": ("video",
        "Alibaba's Apache-2.0 SOTA open video suite (T2V/I2V, MoE, 5B runs on consumer GPUs); the default open video model family in 2026.",
        "Primary open video spoke (text->video, image->video) through ComfyUI or diffusers."),
    "Lightricks/LTX-Video": ("video",
        "Real-time-class DiT video generation (30 FPS faster than playback on H100); production-oriented with keyframe conditioning.",
        "Fast-preview video spoke: near-realtime animatics before committing to heavier Wan/Hunyuan renders."),
    "hpcaitech/Open-Sora": ("video",
        "Fully open video generation stack (weights, training code, data pipeline) democratizing Sora-style models.",
        "Research/self-training spoke; useful when Helix users want to fine-tune house-style video models."),
    "lllyasviel/FramePack": ("video",
        "Next-frame-section prediction that makes long video generation feasible on 6GB VRAM laptops.",
        "Low-VRAM video spoke tier so BYOK users without big GPUs still get local video."),
    "KwaiVGI/LivePortrait": ("video",
        "Efficient portrait animation with stitching and retargeting control (Kuaishou/Kling research).",
        "Talking-head/avatar spoke: animate brand mascots and spokesperson stills from audio/driving video."),
    "remotion-dev/remotion": ("video",
        "Write videos programmatically in React: parametric motion graphics, server-side rendering, Lambda farm.",
        "Loom's motion-graphics compositor: templated brand intros/outros/social cuts rendered from JSON props."),
    "OpenCut-app/OpenCut": ("video",
        "Fast-growing open-source CapCut alternative (timeline editor, privacy-first, web/desktop).",
        "Embedded timeline editor for human touch-up after agent assembly; export/import loom compositions."),

    # ---------------- Audio ----------------
    "coqui-ai/TTS": ("audio",
        "The classic deep-learning TTS toolkit (XTTS-v2 voice cloning in 17 languages); company gone but the idiap fork keeps it alive.",
        "Baseline multilingual TTS/cloning spoke; XTTS-v2 for quick voiceover drafts."),
    "SWivid/F5-TTS": ("audio",
        "Flow-matching TTS with fluent, faithful zero-shot voice cloning; strong quality/speed balance, active in 2026.",
        "Primary voice-clone spoke for narrated brand videos and localized voiceovers."),
    "facebookresearch/audiocraft": ("audio",
        "Meta's audio generation library: MusicGen (controllable music) and AudioGen (sound effects).",
        "Music/SFX spoke: background beds and UI sounds generated to brief; MIT code, weights CC-BY-NC."),
    "fishaudio/fish-speech": ("audio",
        "SOTA open multilingual TTS (OpenAudio S1 lineage) with strong emotion control and low-latency serving.",
        "High-quality expressive TTS spoke where its research license fits the deployment."),
    "RVC-Boss/GPT-SoVITS": ("audio",
        "Few-shot voice cloning (1-minute samples) with cross-lingual inference and a full WebUI toolkit; massive community.",
        "Character-voice spoke for mascots and dubbing; MIT licensed."),
    "openai/whisper": ("audio",
        "The reference robust speech-recognition model; multilingual STT + translation.",
        "Canonical STT weights; used by the transcription spoke for voice-note briefs and video captioning."),
    "ggml-org/whisper.cpp": ("audio",
        "Dependency-free C/C++ Whisper inference running on CPU/Metal/CUDA; ideal for local-first deployment.",
        "Local STT spoke: realtime mic capture on the board ('talk to your canvas') without any API key."),
    "resemble-ai/chatterbox": ("audio",
        "Production-grade open TTS (MIT) with emotion exaggeration control and built-in watermarking; benchmarked against ElevenLabs.",
        "Default English TTS spoke: expressive reads with responsible-AI watermark for client deliverables."),
    "hexgrad/kokoro": ("audio",
        "82M-parameter Apache TTS that is absurdly fast and cheap to run; ONNX/JS ports run in-browser.",
        "Instant-preview TTS: browser-side kokoro for scratch reads before committing to heavier voices."),

    # ---------------- 3D ----------------
    "Tencent-Hunyuan/Hunyuan3D-2": ("3d",
        "Leading open image/text-to-3D system (shape + PBR texture synthesis) with studio UI and blender addon.",
        "Hero 3D-asset spoke: product mockups and mascot meshes; check Hunyuan community license terms."),
    "VAST-AI-Research/TripoSR": ("3d",
        "Fast feed-forward single-image-to-3D reconstruction (MIT, ~0.5s on GPU) from Tripo + Stability.",
        "Quick-draft 3D spoke: instant mesh from a single generated image for scene blocking."),
    "microsoft/TRELLIS": ("3d",
        "Microsoft's structured-latent 3D generator producing meshes, radiance fields and 3D Gaussians from text/image.",
        "Quality 3D spoke tier above TripoSR; outputs GLB straight into the three.js viewer."),
    "graphdeco-inria/gaussian-splatting": ("3d",
        "The original 3D Gaussian Splatting reference (SIGGRAPH 2023) for real-time radiance-field rendering. License is research/non-commercial - integrate ideas, not code, for commercial use.",
        "Reference tech for photoreal scene capture; use MIT reimplementations (e.g. gsplat) in production spokes."),
    "nerfstudio-project/nerfstudio": ("3d",
        "Modular NeRF/3DGS training and viewer framework with clean Python APIs and an active plugin ecosystem.",
        "Photogrammetry spoke: turn client product photos into orbitable 3D for canvas placement."),
    "mrdoob/three.js": ("3d",
        "The standard JavaScript 3D library; renderer for every GLB/GLTF asset on the web.",
        "Board's 3D viewport: preview and stage generated meshes/splats inline on the canvas."),
    "pmndrs/react-three-fiber": ("3d",
        "React renderer for three.js: declarative, componentized 3D scenes with a huge helper ecosystem (drei).",
        "How the board embeds three.js: 3D canvas nodes as React components synced with app state."),
    "ahujasid/blender-mcp": ("3d",
        "MCP server that lets Claude/LLMs drive Blender (scene creation, materials, PolyHaven assets) - viral proof of agent-driven DCC control.",
        "Pro-3D escape hatch: conductor delegates complex modeling/render jobs to Blender through MCP."),

    # ---------------- Infinite canvas / editors ----------------
    "tldraw/tldraw": ("infinite-canvas-editor",
        "Production-grade infinite canvas SDK (React) with multiplayer sync, custom shapes and the famous 'make real' AI demos.",
        "The board itself: Helix canvas is a tldraw instance with custom asset/gen-node shape types."),
    "excalidraw/excalidraw": ("infinite-canvas-editor",
        "Beloved MIT virtual whiteboard with hand-drawn aesthetic, embeddable React component and E2E-encrypted collab.",
        "Alternative board engine; also great for agent-generated wireframe/moodboard sketches."),
    "xyflow/xyflow": ("infinite-canvas-editor",
        "React Flow / Svelte Flow: the standard for node-based UIs (workflow builders, pipelines, DAG editors).",
        "Loom's visual editor: users see and rewire the generation pipeline (prompt -> model -> post) as nodes."),
    "konvajs/konva": ("infinite-canvas-editor",
        "2D canvas scene-graph library (layering, hit detection, transforms) for HTML5 canvas apps.",
        "Board rendering primitive if building a custom canvas instead of tldraw; powers polotno-style editors."),
    "fabricjs/fabric.js": ("infinite-canvas-editor",
        "Canvas object model with interactive transforms and JSON/SVG serialization; the engine behind many web design editors.",
        "Deterministic layout renderer: agent emits fabric JSON, humans tweak it, loom exports SVG/PNG."),
    "pixijs/pixijs": ("infinite-canvas-editor",
        "The fastest WebGL/WebGPU 2D renderer; used for creative tooling at scale.",
        "Performance tier for the board when canvases hold thousands of generated assets."),
    "toeverything/AFFiNE": ("infinite-canvas-editor",
        "Local-first knowledge base fusing docs + infinite whiteboard (edgeless mode) with CRDT sync (BlockSuite).",
        "Architecture reference for local-first board persistence and doc<->canvas duality; BlockSuite is reusable."),
    "onlook-dev/onlook": ("infinite-canvas-editor",
        "'Cursor for designers': open-source visual editor that manipulates live React/Tailwind code in a Figma-like canvas.",
        "Blueprint for Helix's design-to-code lane; potential spoke to hand off web-design artifacts."),

    # ---------------- Design systems ----------------
    "shadcn-ui/ui": ("design-system",
        "Copy-paste component distribution built on Radix + Tailwind; the default UI substrate of the AI-app era and the format LLMs generate best.",
        "Helix's own UI kit, and the target vocabulary when agents generate UI mockups/code."),
    "radix-ui/primitives": ("design-system",
        "Unstyled, accessible React primitives underpinning shadcn/ui.",
        "Accessibility base for all board chrome (dialogs, menus, popovers) without design lock-in."),
    "storybookjs/storybook": ("design-system",
        "Industry-standard workshop for building/documenting UI components in isolation.",
        "QA surface: agent-generated components render into Storybook stories for visual regression review."),
    "mui/material-ui": ("design-system",
        "The most-used React component library (Material Design) with a mature theming engine.",
        "Optional target vocabulary when clients require Material; theming schema informs brand-token mapping."),
    "mantinedev/mantine": ("design-system",
        "Full-featured React components + hooks library with excellent dark-mode and form primitives.",
        "Alternative component target; its hooks library is useful inside Helix's own front-end."),
    "tailwindlabs/tailwindcss": ("design-system",
        "Utility-first CSS framework; the lingua franca of AI-generated styling.",
        "Style substrate: brand kits compile to Tailwind theme tokens the agents reference in all UI output."),
    "penpot/penpot": ("design-system",
        "The open-source design & prototyping platform (Figma alternative), self-hostable, with SVG-native files and plugin API.",
        "Design-file interchange target: loom exports editable Penpot files so humans finish in a real tool."),
    "ant-design/ant-design": ("design-system",
        "Enterprise-grade React design language with the deepest component catalog.",
        "Target vocabulary for enterprise/dashboard deliverables generated by the design agents."),

    # ---------------- Brand kits ----------------
    "simple-icons/simple-icons": ("brand-kit",
        "3300+ SVG brand icons with official brand colors, CC0 - the canonical machine-readable brand-mark dataset.",
        "Brand-kit spoke data: auto-populate competitor/partner logos and validate brand colors."),
    "lucide-icons/lucide": ("brand-kit",
        "Community icon toolkit (Feather successor) with 1500+ consistent icons and per-framework packages.",
        "Default product-icon set injected into generated UI comps and brand sheets."),
    "iconify/iconify": ("brand-kit",
        "Unified framework over 200k+ icons from 150+ sets with one API/component.",
        "Icon search spoke: agents query Iconify API to pick iconography matching a brand's style."),
    "fontsource/fontsource": ("brand-kit",
        "Self-hostable npm packages for every Google Font + more; deterministic, offline-friendly typography.",
        "Typography spoke: brand kits pin fontsource packages so renders are reproducible without Google CDN."),
    "pheralb/svgl": ("brand-kit",
        "Curated library of SVG logos with search API; the go-to for crisp vendor/tech logos.",
        "Logo lookup spoke for pitch decks and integration diagrams."),
    "lokesh/color-thief": ("brand-kit",
        "Extract dominant colors and palettes from images in JS/Node.",
        "Brand-extraction spoke step 1: derive palettes from uploaded client assets to seed the brand kit."),
    "vercel/satori": ("brand-kit",
        "HTML/CSS (JSX) to SVG at incredible speed; the engine behind OG-image generation everywhere.",
        "Deterministic brand-asset renderer: social cards, banners and quote graphics from templates + tokens."),

    # ---------------- Local-first BYOK studios ----------------
    "open-webui/open-webui": ("local-first-byok-studio",
        "The most popular self-hosted AI interface: offline-capable, Ollama + any OpenAI-compatible API, RBAC, pipelines plugin system.",
        "Reference for BYOK settings UX, model management and its 'Pipelines' plugin bus."),
    "lobehub/lobehub": ("local-first-byok-studio",
        "Modern open agent workspace (formerly LobeChat): multi-provider BYOK, plugin marketplace, artifacts, knowledge base, image gen.",
        "Closest existing product to a Lovart-lite; mine its provider-config schema and artifact rendering."),
    "danny-avila/LibreChat": ("local-first-byok-studio",
        "Enhanced multi-provider chat platform: agents, MCP, code interpreter, DALL-E/SD image tools, full BYOK key management per user.",
        "Reference for per-user encrypted key storage (keyring) and its agent/tool marketplace model."),
    "Mintplex-Labs/anything-llm": ("local-first-byok-studio",
        "All-in-one desktop + docker AI app: private RAG workspaces over any LLM (local or API), agents, no-code skills.",
        "Pattern for desktop-first distribution and workspace-scoped memory isolation."),
    "janhq/jan": ("local-first-byok-studio",
        "Offline-first ChatGPT alternative (Apache-2.0) running local models via llama.cpp with optional cloud keys.",
        "Reference for local model lifecycle (download/quantize/run) inside a polished desktop shell."),
    "CherryHQ/cherry-studio": ("local-first-byok-studio",
        "Desktop LLM client supporting dozens of providers + local models, assistants, knowledge bases, MCP; huge momentum in 2025-26.",
        "Reference for multi-provider assistant presets and MCP integration in a desktop BYOK app."),
    "chatboxai/chatbox": ("local-first-byok-studio",
        "Long-standing cross-platform desktop client for many providers with local data storage.",
        "Baseline BYOK desktop UX; informs minimal keyring settings surface."),
    "ollama/ollama": ("local-first-byok-studio",
        "The standard for running LLMs locally with an OpenAI-compatible server; one-line model pulls.",
        "The 'no-key' spoke: Helix treats a local Ollama endpoint as just another keyring provider."),
    "ggml-org/llama.cpp": ("local-first-byok-studio",
        "The engine of local inference (GGUF, CPU/Metal/CUDA) powering Ollama, Jan and countless apps; includes its own OpenAI-compatible server.",
        "Embedded fallback runtime for fully-offline Helix installs (llama-server as a spoke)."),
    "langgenius/dify": ("local-first-byok-studio",
        "Production platform for agentic workflows: visual pipeline builder, RAG, model-agnostic BYOK, observability built in.",
        "Benchmark for the whole studio; its workflow-node taxonomy informs loom's node palette."),
    "n8n-io/n8n": ("local-first-byok-studio",
        "Fair-code workflow automation with 400+ integrations and native AI agent nodes; the glue layer of self-hosted AI stacks.",
        "Automation spoke: publish finished assets to CMS/socials/storage via n8n webhooks from loom."),

    # ---------------- Observability / quota ----------------
    "langfuse/langfuse": ("observability-quota",
        "Leading open LLM engineering platform: traces, evals, prompt management, cost/usage metrics; OTel-based, self-hostable.",
        "Primary observability: LiteLLM + LangGraph callbacks stream every generation to Langfuse; cost per canvas."),
    "Helicone/helicone": ("observability-quota",
        "One-line proxy-based LLM observability with caching, rate limiting and cost tracking (Apache-2.0).",
        "Drop-in quota guard: route keyring traffic through Helicone when users want zero-code metering."),
    "Arize-ai/phoenix": ("observability-quota",
        "Open-source AI observability + evaluation (OTel-native tracing, dataset experiments, eval library).",
        "Eval harness for conductor prompts (brief adherence, style consistency scoring)."),
    "traceloop/openllmetry": ("observability-quota",
        "OpenTelemetry instrumentation for LLM providers, vector DBs and frameworks; export to any OTel backend.",
        "Instrumentation layer: one SDK call auto-traces spokes into whatever backend the deployer already runs."),
    "openlit/openlit": ("observability-quota",
        "OTel-native GenAI observability incl. GPU monitoring, guardrails, prompt hub and cost tracking.",
        "Self-hosted metrics option adding GPU telemetry for local diffusion/video spokes."),
    "promptfoo/promptfoo": ("observability-quota",
        "Test-driven LLM development: prompt evals, regression testing and red-teaming in CI.",
        "CI gate: every conductor prompt/pipeline change runs promptfoo suites before release."),
    "comet-ml/opik": ("observability-quota",
        "Fast-growing open platform for tracing, evals and guardrails across dev->prod (Comet).",
        "Alternative all-in-one observability if teams already use Comet; strong agent-trace UI."),
}

rows = []
for key, (cat, why, integ) in CATALOG.items():
    d = data.get(key)
    if d is None:
        raise SystemExit(f"missing data for {key}")
    repo = d["repo"]
    lic = LICENSE_OVERRIDES.get(repo, LICENSE_OVERRIDES.get(key, d["license"]))
    rows.append({
        "repo": repo,
        "stars_approx": d["stars"],
        "license": lic,
        "category": cat,
        "why": why,
        "integrate_as": integ,
        "url": f"https://github.com/{repo}",
    })

rows.sort(key=lambda r: -r["stars_approx"])
for i, r in enumerate(rows, 1):
    r["rank"] = i
rows = [{k: r[k] for k in ["rank", "repo", "stars_approx", "license", "category", "why", "integrate_as", "url"]} for r in rows]

assert len(rows) == 100, f"expected 100, got {len(rows)}"
json.dump(rows, open("/tmp/atelier-fable/02-top100/top100.json", "w"), indent=2)

from collections import Counter
print(Counter(r["category"] for r in rows))
print("total:", len(rows))
